<script>
export default {}
</script>

<template>
  <nav class="navbar">
    <div class="flex items-center">
      <nuxt-link
        to="/"
        class="navbar-logo"
        exact-active-class="no-active-style"
      >
        <img
          class="navbar-logo-image"
          src="~/assets/avatar.png"
          alt="Your Logo"
        />
        YOUR BRAND HERE
      </nuxt-link>
    </div>
    <div class="navbar-item-wrapper">
      <nuxt-link to="/" class="navbar-item">Home</nuxt-link>
      <nuxt-link to="/blog" class="navbar-item">Blog</nuxt-link>
      <nuxt-link to="/uses" class="navbar-item">Uses</nuxt-link>
    </div>
  </nav>
</template>

<style lang="scss">
@import '../styles/_settings.scss';

.navbar {
  @apply py-3 px-5;
  border-bottom: 2px solid $c-border;
  color: $c-nav-link;
  font-family: $ff-sans;

  @include breakpoint($bk-navbar) {
    @apply flex justify-between items-center;
  }
}

.navbar-item {
  @apply mr-5;
  font-size: 0.9rem;
  @apply font-medium;

  &:last-child {
    @apply mr-0;
  }

  &:hover {
    border-bottom: 2px solid $c-primary;
  }
}

.navbar-item-wrapper {
  @apply text-center;
}

.navbar-logo {
  @apply flex items-center;
  @apply mx-auto mb-3;
  font-size: 1.3rem;
  @apply font-semibold;

  @include breakpoint($bk-navbar) {
    @apply mb-0;
  }
}

.navbar-logo-image {
  @apply inline-block;
  width: 36px;
  @apply mr-3;
}

// Generated by Nuxt Router
.nuxt-link-exact-active {
  border-bottom: 2px solid $c-primary;
}
</style>
